name: library_system
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  mysql_client: ^0.0.27 
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  dart_jsonwebtoken: ^2.5.0
  logger: ^1.1.0
  mongo_dart: ^0.8.0
  encrypt: ^5.0.1
  intl: any
  uuid: ^3.0.6

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0
